{{- if and .Values.backend.adminPassword .Values.backend.sessionSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nathalie-lopez.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-password: {{ .Values.backend.adminPassword | quote }}
  session-secret: {{ .Values.backend.sessionSecret | quote }}
{{- end }}
