apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nathalie-lopez.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "nathalie-lopez.appSelector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nathalie-lopez.appSelector" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret }}
      nodeSelector:
        {{- toYaml .Values.app.nodeSelector | nindent 8 }}
      containers:
        - name: app
          image: "{{ .Values.app.image }}:amd64-v{{ .Values.app.version }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
