apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nathalie-lopez.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "nathalie-lopez.appSelector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: 80
